
version: 2


sources:
  - name: NBA_SHOOTING
    database: SNOWFLAKE_LEARNING_DB
    schema: NBA_SHOOTING
    tables:
      - name: NBA_2425

      - name: NBA_2324

     
models:
  - name: stg_nba_2324
    description: "Staging for 23-24 NBA shooting data"
    columns:
      - name: Player
        description: "the name of the NBA player"
        tests:
          - not_null
          - unique
  
  - name: stg_nba_2425
    description: "Staging for 24-25 NBA shooting data"
    columns:
      - name: Player
        description: "the name of the NBA player"
        tests:
          - not_null
          - unique
  
  - name: int_nba_player_season_compare
    description: "Intermediate model joining player rows across seasons for year-over-year comparison."

  - name: mart_nba_3pfg_jump
    description: "Mart: Ranks players by their 3-point shooting percentage improvement year-over-year."
