
version: 2


sources:
  - name: TPCH_SF10
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF10
    tables:
      - name: CUSTOMER
        description: "Customer information"
        columns:
          - name: C_CUSTKEY
            description: "Primary key for customer"
            tests:
              - unique
              - not_null
      - name: LINEITEM
        description: "Line items for orders"
        columns:
          - name: L_ORDERKEY
            description: "Foreign key to orders"
            tests:
              - not_null
          - name: L_LINENUMBER
            description: "Line number within order"
            tests:
              - not_null
      - name: NATION
        description: "Nation information"
        columns:
          - name: N_NATIONKEY
            description: "Primary key for nation"
            tests:
              - unique
              - not_null
      - name: ORDERS
        description: "Orders placed by customers"
        columns:
          - name: O_ORDERKEY
            description: "Primary key for orders"
            tests:
              - unique
              - not_null
      - name: PART
        description: "Parts available for sale"
        columns:
          - name: P_PARTKEY
            description: "Primary key for part"
            tests:
              - unique
              - not_null
      - name: PARTSUPP
        description: "Supplier parts information"
        columns:
          - name: PS_PARTKEY
            description: "Foreign key to part"
            tests:
              - not_null
          - name: PS_SUPPKEY
            description: "Foreign key to supplier"
            tests:
              - not_null
      - name: REGION
        description: "Region information"
        columns:
          - name: R_REGIONKEY
            description: "Primary key for region"
            tests:
              - unique
              - not_null
      - name: SUPPLIER
        description: "Supplier information"
        columns:
          - name: S_SUPPKEY
            description: "Primary key for supplier"
            tests:
              - unique
              - not_null
models:
  - name: customer_count_by_nation
    description: "the count of customers by nation"
    columns:
      - name: nation_name
        description: "The name of the nation"
        tests:
          - unique
          - not_null
      - name: num_customers
        description: "The number of customers"
        tests:
          - not_null
          - expression_is_true:
             arguments:
               expression: "num_customers >= 0"
          